name: student_app
description: "EduVerse Student Attendance App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3
  intl: ^0.19.0
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  animations: ^2.0.11
  flutter_slidable: ^3.1.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.2
  dio: ^5.4.1
  shimmer: ^3.0.0
  mobile_scanner: ^5.2.3
  install_plugin: ^2.1.0
  open_file: ^3.3.2
  flutter_local_notifications: ^17.2.2
  flutter_dotenv: ^5.1.0
  workmanager: ^0.7.0
  file_picker: ^8.1.4
  share_plus: ^10.1.2
  flutter_email_sender: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Gemini_Generated_Image_imjlkgimjlkgimjl.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
